---
# Playbook to generate configuration of IOSXE device
  - name: Generate first config from Jinja2
    hosts: all
    tasks:
      - include_vars:
         file: group_vars/ent.yml
      - name: Enterprise Config
        template:
          src: "templates/template1.j2"  
          dest: "completed_configs/{{inventory_hostname}}.cfg"
        delegate_to: localhost

